version: '3.2'
services:

  db:
    container_name: client-connect-db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netflix_db
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - app-network
    volumes:
      - client_connect_db:/var/lib/mysql/data

volumes:
  client_connect_db:
    external: false

networks:
  app-network:
    driver: bridge
